apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: "A simple service for user management."
  tags:
    - example
    - user
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  lifecycle: experimental
  owner: team-a
